# Generated by Django 4.1.3 on 2022-11-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usu', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('email_usu', models.EmailField(max_length=50, unique=True)),
                ('tel_usu', models.CharField(max_length=15)),
                ('contrasenna', models.CharField(max_length=16)),
                ('last_login', models.DateTimeField()),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
